import React, { useState, useMemo, useEffect } from 'react';
import { 
  UserPlus, 
  ShieldCheck, 
  Mail, 
  Phone, 
  MapPin,
  Target,
  Trash2,
  UserCog,
  Search,
  CheckCircle2,
  Edit3,
  Users,
  Building,
  UserCheck,
  Award,
  Filter,
  X,
  Sparkles,
  Link as LinkIcon,
  Shield,
  ShieldAlert,
  Lock,
  Eye,
  EyeOff,
  AlertTriangle,
  ArrowRight,
  UserMinus,
  Table as TableIcon,
  LayoutGrid
} from 'lucide-react';
import { useSomiti } from '../../context/SomitiContext';
import { useLanguage } from '../../context/LanguageContext';
import { UserRole, AppUser, Member } from '../../types';
import { toBengaliNumber, formatCurrency } from '../../utils/bengaliUtils';
import { 
  generateNextUserUid, 
  canPromoteToAdmin, 
  canDemoteOrDeactivateAdmin, 
  canDeleteUser,
  getActiveAdminCount,
  MAX_ACTIVE_ADMINS,
  MIN_ACTIVE_ADMINS 
} from '../../utils/userUtils';
import { createAuthAccountWithoutSignout } from '../../lib/firebase';

export const UserManagementView: React.FC = () => {
  const { users, addUser, updateUser, deleteUser, toggleUserStatus, currentUser, members, setSelectedMemberId, setActiveTab } = useSomiti();
  const { language } = useLanguage();
  const isBn = language === 'bn';

  // Modals state
  const [showAddModal, setShowAddModal] = useState(false);
  const [userToDelete, setUserToDelete] = useState<string | null>(null);
  const [editingUser, setEditingUser] = useState<AppUser | null>(null);

  // Filter, View & Search state
  const [searchQuery, setSearchQuery] = useState('');
  const [roleFilter, setRoleFilter] = useState<'all' | 'admin' | 'committee' | 'manager' | 'field_officer' | 'members'>('all');
  const [viewMode, setViewMode] = useState<'table' | 'grid'>('table');
  const [adminWarning, setAdminWarning] = useState<string | null>(null);

  // Add User Form State (Rule 1 & 2)
  const [creationMode, setCreationMode] = useState<'member' | 'direct'>('member');
  const [memberSearch, setMemberSearch] = useState('');
  const [selectedMember, setSelectedMember] = useState<Member | null>(null);

  const [autoGeneratedUid, setAutoGeneratedUid] = useState('');
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [phone, setPhone] = useState('');
  const [assignedArea, setAssignedArea] = useState('');
  const [dailyTarget, setDailyTarget] = useState<number>(0);
  const [avatarUrl, setAvatarUrl] = useState('');
  const [formError, setFormError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Edit User Form State
  const [editRole, setEditRole] = useState<UserRole>('member');
  const [editRoleTitle, setEditRoleTitle] = useState('');
  const [editName, setEditName] = useState('');
  const [editPhone, setEditPhone] = useState('');
  const [editEmail, setEditEmail] = useState('');
  const [editArea, setEditArea] = useState('');
  const [editTarget, setEditTarget] = useState<number>(0);
  const [editStatus, setEditStatus] = useState<'active' | 'inactive'>('active');
  const [editError, setEditError] = useState<string | null>(null);

  // Count active admins
  const activeAdminCount = useMemo(() => getActiveAdminCount(users), [users]);

  // Open Add Modal and auto-generate unique BS-#### UID (Rule 1)
  const handleOpenAddModal = () => {
    resetAddForm();
    const nextUid = generateNextUserUid(users);
    setAutoGeneratedUid(nextUid);
    setShowAddModal(true);
  };

  const getDefaultRoleTitle = (r: UserRole): string => {
    switch (r) {
      case 'admin':
        return isBn ? 'প্রধান প্রশাসক (Admin)' : 'Admin';
      case 'president':
        return isBn ? 'সভাপতি (President)' : 'President';
      case 'secretary':
        return isBn ? 'সাধারণ সম্পাদক (General Secretary)' : 'General Secretary';
      case 'cashier':
        return isBn ? 'ক্যাশিয়ার (Cashier)' : 'Cashier';
      case 'manager':
        return isBn ? 'ম্যানেজার (Manager)' : 'Manager';
      case 'field_officer':
        return isBn ? 'মাঠকর্মী / কালেক্টর' : 'Field Officer';
      case 'member':
      default:
        return isBn ? 'সদস্য (Member)' : 'Member';
    }
  };

  const getRoleBadge = (r: UserRole, customTitle?: string) => {
    switch (r) {
      case 'admin':
        return { 
          label: customTitle || (isBn ? 'প্রধান প্রশাসক (Admin)' : 'Admin'), 
          bg: 'bg-purple-100 text-purple-800 border-purple-200',
          dot: 'bg-purple-500'
        };
      case 'president':
        return { 
          label: customTitle || (isBn ? 'সভাপতি' : 'President'), 
          bg: 'bg-indigo-100 text-indigo-800 border-indigo-200',
          dot: 'bg-indigo-500'
        };
      case 'secretary':
        return { 
          label: customTitle || (isBn ? 'সাধারণ সম্পাদক' : 'General Secretary'), 
          bg: 'bg-blue-100 text-blue-800 border-blue-200',
          dot: 'bg-blue-500'
        };
      case 'cashier':
        return { 
          label: customTitle || (isBn ? 'ক্যাশিয়ার' : 'Cashier'), 
          bg: 'bg-emerald-100 text-emerald-800 border-emerald-200',
          dot: 'bg-emerald-500'
        };
      case 'manager':
        return { 
          label: customTitle || (isBn ? 'ম্যানেজার' : 'Manager'), 
          bg: 'bg-teal-100 text-teal-800 border-teal-200',
          dot: 'bg-teal-500'
        };
      case 'field_officer':
        return { 
          label: customTitle || (isBn ? 'মাঠকর্মী' : 'Field Officer'), 
          bg: 'bg-amber-100 text-amber-800 border-amber-200',
          dot: 'bg-amber-500'
        };
      case 'member':
      default:
        return { 
          label: customTitle || (isBn ? 'সদস্য (Member)' : 'Member'), 
          bg: 'bg-slate-100 text-slate-700 border-slate-200',
          dot: 'bg-slate-400'
        };
    }
  };

  // Filter members for selection in Add Modal
  const filteredEligibleMembers = useMemo(() => {
    if (!memberSearch.trim()) return members.slice(0, 10);
    const q = memberSearch.toLowerCase().trim();
    return members.filter(m => 
      m.name?.toLowerCase().includes(q) ||
      m.nameEn?.toLowerCase().includes(q) ||
      m.memberNo?.toLowerCase().includes(q) ||
      m.phone?.includes(q) ||
      m.email?.toLowerCase().includes(q)
    ).slice(0, 10);
  }, [members, memberSearch]);

  // Rule 5: Check if the selected member already has an account
  const existingAccountForSelectedMember = useMemo(() => {
    if (!selectedMember) return null;
    return users.find(u => u.memberId === selectedMember.id);
  }, [selectedMember, users]);

  // Handle selecting an existing member (Rule 3: sync email, name, phone)
  const handleSelectMember = (member: Member) => {
    setSelectedMember(member);
    setName(member.name);
    setPhone(member.phone || '');
    const cleanMemberEmail = member.email || '';
    setEmail(cleanMemberEmail);
    setAvatarUrl(member.photoUrl || '');
    setAssignedArea(member.presentAddress || (isBn ? 'সাধারণ সদস্য' : 'Somiti Member'));
    setFormError(null);
  };

  // Reset Add Form
  const resetAddForm = () => {
    setSelectedMember(null);
    setMemberSearch('');
    setAutoGeneratedUid('');
    setName('');
    setEmail('');
    setPassword('');
    setConfirmPassword('');
    setShowPassword(false);
    setShowConfirmPassword(false);
    setPhone('');
    setAssignedArea('');
    setDailyTarget(0);
    setAvatarUrl('');
    setFormError(null);
    setCreationMode('member');
    setIsSubmitting(false);
  };

  // Handle Add User Form Submission
  const handleAddUser = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    // Rule 5: Check 1:1 constraint
    if (selectedMember && existingAccountForSelectedMember) {
      setFormError(isBn 
        ? `এই সদস্যের জন্য ইতিমধ্যে একটি অ্যাকাউন্ট (${existingAccountForSelectedMember.userUid || existingAccountForSelectedMember.id}) নিবন্ধিত রয়েছে!` 
        : `This member already has an account (${existingAccountForSelectedMember.userUid || existingAccountForSelectedMember.id})!`
      );
      return;
    }

    if (!name.trim() || !email.trim()) {
      setFormError(isBn ? 'অনুগ্রহ করে নাম এবং ইমেইল ঠিকানা দিন।' : 'Please provide name and email address.');
      return;
    }

    if (!password) {
      setFormError(isBn ? 'পাসওয়ার্ড প্রদান করা আবশ্যক।' : 'Password is required.');
      return;
    }

    if (password.length < 6) {
      setFormError(isBn ? 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।' : 'Password must be at least 6 characters.');
      return;
    }

    if (password !== confirmPassword) {
      setFormError(isBn ? 'কনফার্ম পাসওয়ার্ড মিলছে না!' : 'Passwords do not match!');
      return;
    }

    setIsSubmitting(true);
    const cleanEmail = email.trim().toLowerCase();
    const finalAvatar = avatarUrl.trim() || (selectedMember?.photoUrl || `https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80`);

    try {
      // Rule 1 & 2: Create account with auto-generated BS-#### UID and Role: Member
      const newUser = addUser({
        name: name.trim(),
        email: cleanEmail,
        phone: phone.trim(),
        role: 'member', // Strictly Member by default
        roleTitle: isBn ? 'সদস্য (Member)' : 'Member',
        assignedArea: assignedArea.trim() || (isBn ? 'সাধারণ সদস্য' : 'Somiti Member'),
        dailyTarget: 0,
        collectedToday: 0,
        status: 'active',
        avatarUrl: finalAvatar,
        userUid: autoGeneratedUid || generateNextUserUid(users),
        memberId: selectedMember ? selectedMember.id : undefined,
        memberNo: selectedMember ? selectedMember.memberNo : undefined,
        createdAt: new Date().toISOString(),
      });

      // Also register credentials with secondary auth app so the user can immediately log in
      createAuthAccountWithoutSignout(cleanEmail, password, name.trim()).catch(err => {
        console.warn("Secondary auth creation notice:", err);
      });

      setShowAddModal(false);
      resetAddForm();
    } catch (err: any) {
      setFormError(err?.message || (isBn ? 'অ্যাকাউন্ট তৈরি করতে সমস্যা হয়েছে।' : 'Failed to create user account.'));
    } finally {
      setIsSubmitting(false);
    }
  };

  // Open Edit Modal
  const openEditModal = (user: AppUser) => {
    setEditingUser(user);
    setEditRole(user.role);
    setEditRoleTitle(user.roleTitle || getDefaultRoleTitle(user.role));
    setEditName(user.name);
    setEditPhone(user.phone || '');
    setEditEmail(user.email);
    setEditArea(user.assignedArea || '');
    setEditTarget(user.dailyTarget || 0);
    setEditStatus(user.status);
    setEditError(null);
  };

  // Handle Edit User Form Submission (Rule 4: sync email to member profile)
  const handleEditUser = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingUser) return;
    setEditError(null);

    // If changing role to admin, check max 2 admins
    if (editRole === 'admin' && editingUser.role !== 'admin') {
      const check = canPromoteToAdmin(users, editingUser.id);
      if (!check.allowed) {
        setEditError(isBn ? check.reasonBn : check.reasonEn);
        return;
      }
    }

    // If changing from admin to other role, check min 1 admin
    if (editingUser.role === 'admin' && editRole !== 'admin') {
      const check = canDemoteOrDeactivateAdmin(users, editingUser.id);
      if (!check.allowed) {
        setEditError(isBn ? check.reasonBn : check.reasonEn);
        return;
      }
    }

    try {
      updateUser(editingUser.id, {
        name: editName.trim(),
        phone: editPhone.trim(),
        email: editEmail.trim().toLowerCase(),
        role: editRole,
        roleTitle: editRoleTitle.trim() || getDefaultRoleTitle(editRole),
        assignedArea: editArea.trim(),
        dailyTarget: Number(editTarget) || 0,
        status: editStatus,
      });
      setEditingUser(null);
    } catch (err: any) {
      setEditError(err?.message || 'Error updating user');
    }
  };

  // Rule 2: Promote user to Admin with max 2 active admin constraint
  const handlePromoteToAdmin = (targetUser: AppUser) => {
    setAdminWarning(null);
    const check = canPromoteToAdmin(users, targetUser.id);
    if (!check.allowed) {
      setAdminWarning(isBn ? check.reasonBn : check.reasonEn);
      return;
    }

    try {
      updateUser(targetUser.id, {
        role: 'admin',
        roleTitle: isBn ? 'প্রধান প্রশাসক (Admin)' : 'Admin'
      });
    } catch (err: any) {
      setAdminWarning(err?.message || 'Admin promotion error');
    }
  };

  // Demote Admin to Member with min 1 active admin constraint
  const handleDemoteAdmin = (targetUser: AppUser) => {
    setAdminWarning(null);
    const check = canDemoteOrDeactivateAdmin(users, targetUser.id);
    if (!check.allowed) {
      setAdminWarning(isBn ? check.reasonBn : check.reasonEn);
      return;
    }

    try {
      updateUser(targetUser.id, {
        role: 'member',
        roleTitle: isBn ? 'সদস্য (Member)' : 'Member'
      });
    } catch (err: any) {
      setAdminWarning(err?.message || 'Demotion error');
    }
  };

  const confirmDelete = (userId: string) => {
    try {
      deleteUser(userId);
      setUserToDelete(null);
    } catch (err: any) {
      setAdminWarning(err?.message || 'Delete error');
      setUserToDelete(null);
    }
  };

  // Filtered Users List
  const filteredUsers = useMemo(() => {
    return users.filter(user => {
      const q = searchQuery.toLowerCase().trim();
      const matchesSearch = !q || 
        user.userUid?.toLowerCase().includes(q) ||
        user.name?.toLowerCase().includes(q) ||
        user.email?.toLowerCase().includes(q) ||
        user.phone?.includes(q) ||
        user.roleTitle?.toLowerCase().includes(q) ||
        (user.memberNo && user.memberNo.toLowerCase().includes(q));

      if (!matchesSearch) return false;

      if (roleFilter === 'all') return true;
      if (roleFilter === 'admin') return user.role === 'admin';
      if (roleFilter === 'committee') return ['president', 'secretary', 'cashier'].includes(user.role);
      if (roleFilter === 'manager') return user.role === 'manager';
      if (roleFilter === 'field_officer') return user.role === 'field_officer';
      if (roleFilter === 'members') return user.role === 'member' || !!user.memberId;

      return true;
    });
  }, [users, searchQuery, roleFilter]);

  // Statistics
  const stats = useMemo(() => {
    const total = users.length;
    const adminCount = users.filter(u => u.role === 'admin' && u.status === 'active').length;
    const committeeCount = users.filter(u => ['president', 'secretary', 'cashier'].includes(u.role)).length;
    const memberAccountsCount = users.filter(u => u.role === 'member' || !!u.memberId).length;
    return { total, adminCount, committeeCount, memberAccountsCount };
  }, [users]);

  return (
    <div className="space-y-6 pb-12">
      {/* Top Header Card */}
      <div className="bg-white p-5 sm:p-6 rounded-2xl border border-slate-200 shadow-2xs">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-3.5">
            <div className="p-3 bg-indigo-50 text-indigo-700 rounded-xl ring-4 ring-indigo-50/50">
              <UserCog className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2.5">
                <h2 className="text-lg font-bold text-slate-900 tracking-tight">
                  {isBn ? 'ব্যবহারকারী অ্যাকাউন্ট ব্যবস্থাপনা' : 'User Account Management'}
                </h2>
                <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-purple-100 text-purple-800 border border-purple-200">
                  {isBn ? `সক্রিয় এডমিন: ${toBengaliNumber(activeAdminCount)}/২` : `Active Admins: ${activeAdminCount}/2`}
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-0.5">
                {isBn 
                  ? `মোট নিবন্ধিত অ্যাকাউন্ট: ${toBengaliNumber(stats.total)} টি • সদস্য লগইন ও রোল নিয়ন্ত্রণ`
                  : `Total registered accounts: ${stats.total} • Member login & role access control`}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2.5">
            {/* View Mode Toggle (Table / Grid) */}
            <div className="flex items-center bg-slate-100 p-1 rounded-xl border border-slate-200">
              <button
                type="button"
                onClick={() => setViewMode('table')}
                title={isBn ? 'টেবিল ভিউ' : 'Table View'}
                className={`p-1.5 rounded-lg text-xs font-bold transition-all ${
                  viewMode === 'table' ? 'bg-white text-indigo-700 shadow-xs' : 'text-slate-500 hover:text-slate-800'
                }`}
              >
                <TableIcon className="w-4 h-4" />
              </button>
              <button
                type="button"
                onClick={() => setViewMode('grid')}
                title={isBn ? 'গ্রিড ভিউ' : 'Grid View'}
                className={`p-1.5 rounded-lg text-xs font-bold transition-all ${
                  viewMode === 'grid' ? 'bg-white text-indigo-700 shadow-xs' : 'text-slate-500 hover:text-slate-800'
                }`}
              >
                <LayoutGrid className="w-4 h-4" />
              </button>
            </div>

            <button
              onClick={handleOpenAddModal}
              className="flex items-center gap-2 px-4 py-2.5 bg-indigo-700 hover:bg-indigo-800 text-white rounded-xl text-xs font-bold shadow-sm hover:shadow-md transition-all active:scale-95 cursor-pointer"
            >
              <UserPlus className="w-4 h-4" />
              <span>{isBn ? 'নতুন অ্যাকাউন্ট তৈরি করুন' : 'Create User Account'}</span>
            </button>
          </div>
        </div>

        {/* Quick Stats Banner */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-5 pt-4 border-t border-slate-100">
          <div className="bg-slate-50/80 rounded-xl p-3 border border-slate-100">
            <div className="text-[11px] font-semibold text-slate-500">
              {isBn ? 'মোট অ্যাকাউন্ট' : 'Total Accounts'}
            </div>
            <div className="text-lg font-extrabold text-slate-800 mt-0.5">
              {isBn ? toBengaliNumber(stats.total) : stats.total}
            </div>
          </div>

          <div className={`rounded-xl p-3 border transition-colors ${
            activeAdminCount >= MAX_ACTIVE_ADMINS 
              ? 'bg-amber-50/80 border-amber-200 text-amber-900' 
              : 'bg-purple-50/60 border-purple-100/80 text-purple-900'
          }`}>
            <div className="text-[11px] font-semibold flex items-center justify-between">
              <span>{isBn ? 'সক্রিয় এডমিন' : 'Active Admins'}</span>
              <span className="text-[10px] px-1.5 py-0.2 rounded bg-purple-200/60 font-mono font-bold">
                Max: {MAX_ACTIVE_ADMINS}
              </span>
            </div>
            <div className="text-lg font-extrabold mt-0.5">
              {isBn ? toBengaliNumber(activeAdminCount) : activeAdminCount} / 2
              <span className="text-[11px] font-normal ml-1.5 opacity-80">
                {activeAdminCount >= MAX_ACTIVE_ADMINS ? (isBn ? '(সর্বোচ্চ সীমা পূর্ণ)' : '(Limit Reached)') : (isBn ? '(খালি আছে)' : '(Available)')}
              </span>
            </div>
          </div>

          <div className="bg-indigo-50/50 rounded-xl p-3 border border-indigo-100/60">
            <div className="text-[11px] font-semibold text-indigo-700">
              {isBn ? 'কমিটি ও কর্মকর্তা' : 'Committee & Staff'}
            </div>
            <div className="text-lg font-extrabold text-indigo-900 mt-0.5">
              {isBn ? toBengaliNumber(stats.committeeCount) : stats.committeeCount}
            </div>
          </div>

          <div className="bg-emerald-50/50 rounded-xl p-3 border border-emerald-100/60">
            <div className="text-[11px] font-semibold text-emerald-700 flex items-center gap-1">
              <Users className="w-3 h-3" />
              <span>{isBn ? 'সদস্য অ্যাকাউন্ট' : 'Member Accounts'}</span>
            </div>
            <div className="text-lg font-extrabold text-emerald-900 mt-0.5">
              {isBn ? toBengaliNumber(stats.memberAccountsCount) : stats.memberAccountsCount}
            </div>
          </div>
        </div>
      </div>

      {/* Admin Limit Warning Alert */}
      {adminWarning && (
        <div className="p-4 bg-amber-50 border border-amber-300 rounded-2xl flex items-start justify-between gap-3 text-amber-900 animate-in fade-in">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <h4 className="text-xs font-bold text-amber-950">
                {isBn ? 'অ্যাডমিন নিরাপত্তা ও সীমাবদ্ধতা নোটিশ' : 'Admin Security Constraint Notice'}
              </h4>
              <p className="text-xs text-amber-800 mt-0.5 leading-relaxed">{adminWarning}</p>
            </div>
          </div>
          <button
            onClick={() => setAdminWarning(null)}
            className="text-amber-600 hover:text-amber-950 p-1 rounded-lg hover:bg-amber-100 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* Search & Filter Toolbar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 bg-white p-3.5 rounded-xl border border-slate-200 shadow-2xs">
        {/* Search Box */}
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder={isBn ? 'User UID (BS-####), নাম, ইমেইল বা সদস্য নং দিয়ে খুঁজুন...' : 'Search by User UID (BS-####), name, email or member no...'}
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-4 py-2 border border-slate-200 rounded-lg text-xs bg-slate-50/50 focus:bg-white focus:ring-2 focus:ring-indigo-500 focus:outline-hidden transition-all"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 cursor-pointer"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          )}
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 md:pb-0 scrollbar-none">
          <button
            onClick={() => setRoleFilter('all')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors cursor-pointer ${
              roleFilter === 'all' 
                ? 'bg-indigo-700 text-white shadow-xs' 
                : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
            }`}
          >
            {isBn ? 'সকল' : 'All'} ({isBn ? toBengaliNumber(users.length) : users.length})
          </button>

          <button
            onClick={() => setRoleFilter('admin')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors cursor-pointer ${
              roleFilter === 'admin' 
                ? 'bg-purple-700 text-white shadow-xs' 
                : 'bg-purple-50 text-purple-700 hover:bg-purple-100'
            }`}
          >
            {isBn ? 'এডমিন' : 'Admins'} ({isBn ? toBengaliNumber(activeAdminCount) : activeAdminCount})
          </button>

          <button
            onClick={() => setRoleFilter('members')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors cursor-pointer ${
              roleFilter === 'members' 
                ? 'bg-emerald-700 text-white shadow-xs' 
                : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'
            }`}
          >
            {isBn ? 'সদস্য একাউন্ট' : 'Members'} ({isBn ? toBengaliNumber(stats.memberAccountsCount) : stats.memberAccountsCount})
          </button>

          <button
            onClick={() => setRoleFilter('committee')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors cursor-pointer ${
              roleFilter === 'committee' 
                ? 'bg-indigo-700 text-white shadow-xs' 
                : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
            }`}
          >
            {isBn ? 'কমিটি' : 'Committee'}
          </button>
        </div>
      </div>

      {/* ========================================================================= */}
      {/* Rule 8: Admin View of Accounts (User Accounts Table) */}
      {/* ========================================================================= */}
      {filteredUsers.length === 0 ? (
        <div className="bg-white p-12 rounded-2xl border border-dashed border-slate-300 text-center space-y-3">
          <div className="w-12 h-12 bg-slate-100 text-slate-400 rounded-full flex items-center justify-center mx-auto">
            <Users className="w-6 h-6" />
          </div>
          <h3 className="text-sm font-bold text-slate-700">
            {isBn ? 'কোনো ব্যবহারকারী অ্যাকাউন্ট পাওয়া যায়নি' : 'No user account found'}
          </h3>
          <p className="text-xs text-slate-500 max-w-sm mx-auto">
            {searchQuery 
              ? (isBn ? 'আপনার অনুসন্ধানের সাথে মিল রয়েছে এমন কোনো অ্যাকাউন্ট পাওয়া যায়নি।' : 'No records match your search criteria.')
              : (isBn ? 'নতুন অ্যাকাউন্ট তৈরি করতে উপরের বাটনে ক্লিক করুন।' : 'Click the button above to create a new user account.')}
          </p>
        </div>
      ) : viewMode === 'table' ? (
        /* TABLE VIEW (Requirement 8) */
        <div className="bg-white rounded-2xl border border-slate-200 shadow-2xs overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/80 border-b border-slate-200 text-[11px] font-bold text-slate-600 uppercase tracking-wider">
                  <th className="py-3.5 px-4">{isBn ? 'ইউজার ইউআইডি (UID)' : 'User UID'}</th>
                  <th className="py-3.5 px-4">{isBn ? 'নাম ও প্রোফাইল' : 'Name'}</th>
                  <th className="py-3.5 px-4">{isBn ? 'ইমেইল এড্রেস' : 'Email Address'}</th>
                  <th className="py-3.5 px-4">{isBn ? 'রোল (Role)' : 'Role'}</th>
                  <th className="py-3.5 px-4">{isBn ? 'সংযুক্ত সদস্য প্রোফাইল' : 'Linked Member'}</th>
                  <th className="py-3.5 px-4 text-center">{isBn ? 'স্ট্যাটাস' : 'Status'}</th>
                  <th className="py-3.5 px-4 text-right">{isBn ? 'অ্যাকশন (Actions)' : 'Actions'}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs">
                {filteredUsers.map((user) => {
                  const roleBadge = getRoleBadge(user.role, user.roleTitle);
                  const isMe = user.id === currentUser?.id || user.email === currentUser?.email;
                  const isUserAdminRole = user.role === 'admin';
                  const linkedMemberObj = user.memberId ? members.find(m => m.id === user.memberId) : null;

                  return (
                    <tr key={user.id} className="hover:bg-slate-50/80 transition-colors">
                      {/* 1. User UID */}
                      <td className="py-3.5 px-4">
                        <span className="font-mono font-bold text-indigo-700 bg-indigo-50 border border-indigo-200/70 px-2.5 py-1 rounded-lg text-xs inline-block">
                          {user.userUid || user.id}
                        </span>
                      </td>

                      {/* 2. Name */}
                      <td className="py-3.5 px-4">
                        <div className="flex items-center gap-3">
                          <img
                            src={user.avatarUrl || `https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80`}
                            alt={user.name}
                            className="w-8 h-8 rounded-full object-cover border border-slate-200 shadow-2xs"
                          />
                          <div>
                            <div className="font-bold text-slate-800 flex items-center gap-1.5">
                              <span>{user.name}</span>
                              {isMe && (
                                <span className="text-[10px] px-1.5 py-0.2 bg-indigo-100 text-indigo-800 font-bold rounded">
                                  {isBn ? 'আপনি' : 'You'}
                                </span>
                              )}
                            </div>
                            {user.phone && (
                              <div className="text-[11px] text-slate-400 font-sans">
                                {isBn ? toBengaliNumber(user.phone) : user.phone}
                              </div>
                            )}
                          </div>
                        </div>
                      </td>

                      {/* 3. Email */}
                      <td className="py-3.5 px-4">
                        <span className="font-mono text-slate-700 text-[11px]">{user.email}</span>
                      </td>

                      {/* 4. Role */}
                      <td className="py-3.5 px-4">
                        <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold border ${roleBadge.bg}`}>
                          <span className={`w-1.5 h-1.5 rounded-full ${roleBadge.dot}`}></span>
                          <span>{roleBadge.label}</span>
                        </span>
                      </td>

                      {/* 5. Linked Member */}
                      <td className="py-3.5 px-4">
                        {user.memberId ? (
                          <div 
                            onClick={() => {
                              setSelectedMemberId(user.memberId!);
                              setActiveTab('member_profile');
                            }}
                            className="inline-flex items-center gap-1.5 text-indigo-700 hover:text-indigo-900 bg-indigo-50/80 hover:bg-indigo-100/70 border border-indigo-200/60 px-2.5 py-1 rounded-lg cursor-pointer transition-colors"
                            title={isBn ? 'সদস্যের বিস্তারিত প্রোফাইল দেখুন' : 'View Member Profile'}
                          >
                            <LinkIcon className="w-3 h-3 text-indigo-600 shrink-0" />
                            <span className="font-semibold">
                              {user.memberNo || (linkedMemberObj?.memberNo ? `#${linkedMemberObj.memberNo}` : '')} - {linkedMemberObj?.name || user.name}
                            </span>
                          </div>
                        ) : (
                          <span className="text-slate-400 italic text-[11px]">
                            {isBn ? 'সরাসরি স্টাফ (সদস্য নন)' : 'Direct Staff'}
                          </span>
                        )}
                      </td>

                      {/* 6. Status */}
                      <td className="py-3.5 px-4 text-center">
                        <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold inline-block ${
                          user.status === 'active' 
                            ? 'bg-emerald-100 text-emerald-800' 
                            : 'bg-rose-100 text-rose-800'
                        }`}>
                          {user.status === 'active' ? (isBn ? 'সক্রিয়' : 'Active') : (isBn ? 'স্থগিত' : 'Inactive')}
                        </span>
                      </td>

                      {/* 7. Actions (Requirement 8) */}
                      <td className="py-3.5 px-4 text-right">
                        <div className="flex items-center justify-end gap-1.5">
                          {/* Promote to Admin / Demote to Member */}
                          {!isUserAdminRole ? (
                            <button
                              type="button"
                              onClick={() => handlePromoteToAdmin(user)}
                              title={activeAdminCount >= MAX_ACTIVE_ADMINS 
                                ? (isBn ? 'সর্বোচ্চ ২টি সক্রিয় এডমিন পূর্ণ' : 'Maximum 2 active Admin accounts reached')
                                : (isBn ? 'এডমিনে উন্নীত করুন' : 'Promote to Admin')}
                              className="px-2.5 py-1 text-[11px] font-bold text-purple-700 bg-purple-50 hover:bg-purple-100 border border-purple-200 rounded-lg flex items-center gap-1 transition-colors cursor-pointer"
                            >
                              <ShieldCheck className="w-3.5 h-3.5 text-purple-600" />
                              <span>{isBn ? 'এডমিন করুন' : 'Promote'}</span>
                            </button>
                          ) : !isMe ? (
                            <button
                              type="button"
                              onClick={() => handleDemoteAdmin(user)}
                              title={isBn ? 'সদস্য হিসেবে পরিবর্তন করুন' : 'Demote to Member'}
                              className="px-2 py-1 text-[11px] font-bold text-slate-600 bg-slate-100 hover:bg-slate-200 border border-slate-300 rounded-lg flex items-center gap-1 transition-colors cursor-pointer"
                            >
                              <UserMinus className="w-3.5 h-3.5 text-slate-500" />
                              <span>{isBn ? 'ডিমোট' : 'Demote'}</span>
                            </button>
                          ) : null}

                          {/* Edit Button */}
                          <button
                            type="button"
                            onClick={() => openEditModal(user)}
                            title={isBn ? 'তথ্য ও পদবী সম্পাদনা' : 'Edit User'}
                            className="p-1.5 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer"
                          >
                            <Edit3 className="w-4 h-4" />
                          </button>

                          {/* Deactivate / Activate Button */}
                          {!isMe && (
                            <button
                              type="button"
                              onClick={() => toggleUserStatus(user.id)}
                              title={user.status === 'active' ? (isBn ? 'স্থগিত করুন' : 'Deactivate') : (isBn ? 'সক্রিয় করুন' : 'Activate')}
                              className={`p-1.5 rounded-lg transition-colors cursor-pointer ${
                                user.status === 'active'
                                  ? 'text-slate-400 hover:text-amber-600 hover:bg-amber-50'
                                  : 'text-emerald-600 hover:bg-emerald-50'
                              }`}
                            >
                              <Lock className="w-4 h-4" />
                            </button>
                          )}

                          {/* Delete Button */}
                          {!isMe && (
                            <button
                              type="button"
                              onClick={() => setUserToDelete(user.id)}
                              title={isBn ? 'অ্যাকাউন্ট মুছুন' : 'Delete Account'}
                              className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors cursor-pointer"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        /* GRID CARDS VIEW */
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredUsers.map((user) => {
            const roleBadge = getRoleBadge(user.role, user.roleTitle);
            const isMe = user.id === currentUser?.id || user.email === currentUser?.email;
            const isUserAdminRole = user.role === 'admin';
            const linkedMemberObj = user.memberId ? members.find(m => m.id === user.memberId) : null;

            return (
              <div
                key={user.id}
                className="bg-white p-5 rounded-2xl border border-slate-200 shadow-2xs space-y-4 hover:border-indigo-200 hover:shadow-md transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-start justify-between gap-3 pb-3 border-b border-slate-100">
                    <div className="flex items-center gap-3">
                      <img
                        src={user.avatarUrl || `https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80`}
                        alt={user.name}
                        className="w-12 h-12 rounded-xl object-cover border border-slate-200 shadow-2xs shrink-0"
                      />
                      <div>
                        <div className="flex items-center gap-1.5">
                          <span className="font-mono text-[11px] font-bold px-2 py-0.5 rounded bg-indigo-50 text-indigo-700 border border-indigo-200">
                            {user.userUid || user.id}
                          </span>
                          {isMe && (
                            <span className="text-[10px] px-1.5 py-0.2 bg-indigo-100 text-indigo-800 font-bold rounded">
                              {isBn ? 'আপনি' : 'You'}
                            </span>
                          )}
                        </div>
                        <h4 className="text-sm font-bold text-slate-800 mt-1">{user.name}</h4>
                        <div className="mt-1">
                          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold border ${roleBadge.bg}`}>
                            <span className={`w-1 h-1 rounded-full ${roleBadge.dot}`}></span>
                            <span>{roleBadge.label}</span>
                          </span>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => openEditModal(user)}
                        title={isBn ? 'সম্পাদনা' : 'Edit'}
                        className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer"
                      >
                        <Edit3 className="w-4 h-4" />
                      </button>
                      {!isMe && (
                        <button
                          onClick={() => setUserToDelete(user.id)}
                          title={isBn ? 'মুছুন' : 'Delete'}
                          className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors cursor-pointer"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </div>

                  {/* Information Rows */}
                  <div className="space-y-1.5 text-xs text-slate-600 pt-3">
                    <div className="flex items-center gap-2">
                      <Mail className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                      <span className="truncate font-mono text-[11px] text-slate-700">{user.email}</span>
                    </div>

                    {user.phone && (
                      <div className="flex items-center gap-2">
                        <Phone className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                        <span className="text-slate-700">{isBn ? toBengaliNumber(user.phone) : user.phone}</span>
                      </div>
                    )}

                    {user.memberId && (
                      <div className="flex items-center gap-2">
                        <LinkIcon className="w-3.5 h-3.5 text-indigo-500 shrink-0" />
                        <span className="text-indigo-700 font-semibold text-[11px]">
                          {user.memberNo || (linkedMemberObj?.memberNo ? `#${linkedMemberObj.memberNo}` : '')} - {linkedMemberObj?.name || user.name}
                        </span>
                      </div>
                    )}
                  </div>
                </div>

                {/* Bottom Actions Bar */}
                <div className="pt-3 border-t border-slate-100 flex items-center justify-between gap-2">
                  <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold ${
                    user.status === 'active' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'
                  }`}>
                    {user.status === 'active' ? (isBn ? 'সক্রিয়' : 'Active') : (isBn ? 'স্থগিত' : 'Inactive')}
                  </span>

                  <div className="flex items-center gap-2">
                    {!isUserAdminRole ? (
                      <button
                        type="button"
                        onClick={() => handlePromoteToAdmin(user)}
                        className="px-2.5 py-1 text-[11px] font-bold text-purple-700 bg-purple-50 hover:bg-purple-100 border border-purple-200 rounded-lg flex items-center gap-1 transition-colors cursor-pointer"
                      >
                        <ShieldCheck className="w-3.5 h-3.5" />
                        <span>{isBn ? 'এডমিন করুন' : 'Promote'}</span>
                      </button>
                    ) : !isMe ? (
                      <button
                        type="button"
                        onClick={() => handleDemoteAdmin(user)}
                        className="px-2 py-1 text-[11px] font-bold text-slate-600 bg-slate-100 hover:bg-slate-200 border border-slate-200 rounded-lg transition-colors cursor-pointer"
                      >
                        <span>{isBn ? 'ডিমোট' : 'Demote'}</span>
                      </button>
                    ) : null}

                    {!isMe && (
                      <button
                        onClick={() => toggleUserStatus(user.id)}
                        className={`text-xs font-bold transition-colors cursor-pointer ${
                          user.status === 'active' ? 'text-rose-600 hover:text-rose-800' : 'text-emerald-600 hover:text-emerald-800'
                        }`}
                      >
                        {user.status === 'active' ? (isBn ? 'স্থগিত' : 'Suspend') : (isBn ? 'সক্রিয়' : 'Activate')}
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* ========================================================================= */}
      {/* Rule 1 & 2: User Account Creation Modal */}
      {/* ========================================================================= */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
          <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 w-full max-w-xl overflow-hidden my-6">
            {/* Modal Header */}
            <div className="bg-indigo-900 text-white px-6 py-4.5 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <div className="p-2 bg-indigo-800 rounded-xl">
                  <UserPlus className="w-5 h-5 text-indigo-200" />
                </div>
                <div>
                  <h3 className="text-base font-bold">
                    {isBn ? 'নতুন ব্যবহারকারী অ্যাকাউন্ট নিবন্ধন' : 'Create New User Account'}
                  </h3>
                  <p className="text-xs text-indigo-200">
                    {isBn ? 'সদস্যের জন্য ডিজিটাল লগইন অ্যাকাউন্ট তৈরি করুন' : 'Register a digital user account for somiti member'}
                  </p>
                </div>
              </div>
              <button 
                onClick={() => {
                  setShowAddModal(false);
                  resetAddForm();
                }} 
                className="text-indigo-200 hover:text-white p-1.5 rounded-lg hover:bg-indigo-800 transition-colors cursor-pointer"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleAddUser} className="p-6 space-y-4.5 max-h-[80vh] overflow-y-auto">
              {/* Form Error Banner */}
              {formError && (
                <div className="p-3.5 bg-rose-50 border border-rose-200 rounded-2xl flex items-start gap-2.5 text-xs text-rose-700 animate-in fade-in">
                  <AlertTriangle className="w-4 h-4 text-rose-500 shrink-0 mt-0.5" />
                  <div className="flex-1 font-medium leading-relaxed">{formError}</div>
                </div>
              )}

              {/* 1. Automatically Generated User UID in BS-#### format (Rule 1) */}
              <div className="bg-indigo-50/60 p-3.5 rounded-2xl border border-indigo-200/70 space-y-1.5">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-bold text-indigo-950 flex items-center gap-1.5">
                    <Shield className="w-4 h-4 text-indigo-600" />
                    <span>{isBn ? 'ইউজার ইউআইডি (User UID)' : 'User UID'}</span>
                  </label>
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-indigo-200 text-indigo-900">
                    {isBn ? 'স্বয়ংক্রিয় ও অনন্য আইডি' : 'Auto-generated & Unique'}
                  </span>
                </div>
                <div className="relative">
                  <input
                    type="text"
                    readOnly
                    value={autoGeneratedUid}
                    className="w-full pl-3 pr-8 py-2.5 bg-white border border-indigo-200 rounded-xl font-mono text-base font-extrabold text-indigo-700 tracking-wider cursor-not-allowed select-all"
                  />
                  <Lock className="w-4 h-4 text-indigo-400 absolute right-3 top-1/2 -translate-y-1/2" />
                </div>
                <p className="text-[10px] text-indigo-700">
                  {isBn 
                    ? 'এই ইউজার ইউআইডি সিস্টেম থেকে স্বয়ংক্রিয়ভাবে BS-#### ফরম্যাটে তৈরি হয়েছে এবং লগইন আইডি হিসেবে ব্যবহার করা যাবে।' 
                    : 'Generated in BS-#### format. Can be used as login ID along with email.'}
                </p>
              </div>

              {/* 2. Linked Member Profile (Rule 3 & Rule 5) */}
              <div className="space-y-2">
                <label className="block text-xs font-bold text-slate-800">
                  {isBn ? 'সংযুক্ত সদস্য প্রোফাইল (Linked Member Profile)' : 'Linked Member Profile'} <span className="text-rose-500">*</span>
                </label>

                {/* Member Search input if not selected */}
                {!selectedMember ? (
                  <div className="space-y-2">
                    <div className="relative">
                      <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                      <input
                        type="text"
                        placeholder={isBn ? 'সদস্যের নাম, সদস্য নং (#), বা মোবাইল নম্বর দিয়ে খুঁজুন...' : 'Search member by name, member no or phone...'}
                        value={memberSearch}
                        onChange={(e) => setMemberSearch(e.target.value)}
                        className="w-full pl-9 pr-4 py-2.5 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
                      />
                    </div>

                    {/* Member selection dropdown list */}
                    <div className="border border-slate-200 rounded-xl overflow-hidden max-h-44 overflow-y-auto divide-y divide-slate-100 bg-white">
                      {filteredEligibleMembers.length === 0 ? (
                        <div className="p-4 text-center text-xs text-slate-500">
                          {isBn ? 'কোনো সদস্য পাওয়া যায়নি।' : 'No members found.'}
                        </div>
                      ) : (
                        filteredEligibleMembers.map((m) => {
                          const existingAcc = users.find(u => u.memberId === m.id);
                          return (
                            <div
                              key={m.id}
                              onClick={() => handleSelectMember(m)}
                              className={`p-2.5 flex items-center justify-between hover:bg-indigo-50/60 cursor-pointer transition-colors ${
                                existingAcc ? 'bg-slate-50/70 opacity-80' : ''
                              }`}
                            >
                              <div className="flex items-center gap-2.5">
                                <img
                                  src={m.photoUrl || `https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80`}
                                  alt={m.name}
                                  className="w-8 h-8 rounded-full object-cover border border-slate-200"
                                />
                                <div>
                                  <div className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
                                    <span>{m.name}</span>
                                    <span className="text-[10px] font-mono text-indigo-700 bg-indigo-50 px-1.5 rounded">
                                      #{isBn ? toBengaliNumber(m.memberNo) : m.memberNo}
                                    </span>
                                  </div>
                                  <div className="text-[10px] text-slate-500">
                                    {m.email ? `ইমেইল: ${m.email} • ` : ''}মোবাইল: {isBn ? toBengaliNumber(m.phone) : m.phone}
                                  </div>
                                </div>
                              </div>

                              <div>
                                {existingAcc ? (
                                  <span className="text-[10px] px-2 py-0.5 bg-amber-100 text-amber-800 rounded font-bold">
                                    {existingAcc.userUid || 'অ্যাকাউন্ট রয়েছে'}
                                  </span>
                                ) : (
                                  <span className="text-[11px] font-bold text-indigo-700 hover:underline">
                                    {isBn ? 'নির্বাচন করুন →' : 'Select →'}
                                  </span>
                                )}
                              </div>
                            </div>
                          );
                        })
                      )}
                    </div>
                  </div>
                ) : (
                  /* Selected Member Card Preview */
                  <div className="space-y-2">
                    <div className="bg-indigo-50/80 p-3.5 rounded-2xl border border-indigo-200 flex items-center justify-between gap-3">
                      <div className="flex items-center gap-3">
                        <img
                          src={selectedMember.photoUrl || `https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80`}
                          alt={selectedMember.name}
                          className="w-11 h-11 rounded-xl object-cover border-2 border-white shadow-2xs"
                        />
                        <div>
                          <div className="flex items-center gap-2">
                            <h4 className="text-xs font-bold text-indigo-950">{selectedMember.name}</h4>
                            <span className="px-1.5 py-0.2 bg-indigo-200 text-indigo-900 rounded text-[10px] font-mono font-bold">
                              #{isBn ? toBengaliNumber(selectedMember.memberNo) : selectedMember.memberNo}
                            </span>
                          </div>
                          <p className="text-[11px] text-indigo-800 mt-0.5">
                            {selectedMember.email ? `${selectedMember.email} • ` : ''}{isBn ? toBengaliNumber(selectedMember.phone) : selectedMember.phone}
                          </p>
                        </div>
                      </div>

                      <button
                        type="button"
                        onClick={() => setSelectedMember(null)}
                        className="text-xs font-bold text-rose-600 hover:text-rose-800 hover:underline shrink-0 cursor-pointer"
                      >
                        {isBn ? 'পরিবর্তন করুন' : 'Change'}
                      </button>
                    </div>

                    {/* Rule 5: Duplicate Account Prevention Banner */}
                    {existingAccountForSelectedMember && (
                      <div className="p-3 bg-amber-50 border border-amber-300 rounded-xl space-y-1.5 text-xs text-amber-900">
                        <div className="flex items-start gap-2">
                          <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                          <div className="font-semibold">
                            {isBn 
                              ? `এই সদস্যের জন্য ইতিমধ্যে একটি অ্যাকাউন্ট রয়েছে (UID: ${existingAccountForSelectedMember.userUid || existingAccountForSelectedMember.id})`
                              : `This member already has an account (UID: ${existingAccountForSelectedMember.userUid || existingAccountForSelectedMember.id})`}
                          </div>
                        </div>
                        <div className="pt-1">
                          <button
                            type="button"
                            onClick={() => {
                              setShowAddModal(false);
                              setSearchQuery(existingAccountForSelectedMember.userUid || existingAccountForSelectedMember.id);
                            }}
                            className="px-3 py-1 bg-amber-600 hover:bg-amber-700 text-white rounded-lg font-bold text-[11px] transition-colors cursor-pointer"
                          >
                            {isBn ? 'বিদ্যমান অ্যাকাউন্ট দেখুন →' : 'View Existing Account →'}
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* 3. Email Address (Rule 3: syncs to member profile) */}
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  {isBn ? 'ইমেইল এড্রেস (লগইন ইমেইল)' : 'Email Address'} <span className="text-rose-500">*</span>
                </label>
                <div className="relative">
                  <Mail className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                  <input
                    type="email"
                    required
                    placeholder="member@bondhusomiti.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full pl-10 pr-4 py-2.5 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
                  />
                </div>
                <p className="text-[10px] text-slate-500 mt-1">
                  {isBn 
                    ? 'এখানে দেওয়া ইমেইল স্বয়ংক্রিয়ভাবে সদস্য প্রোফাইলেও সিঙ্ক হয়ে যাবে।' 
                    : 'This email will automatically synchronize to the linked member profile.'}
                </p>
              </div>

              {/* 4. Password & Confirm Password */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {isBn ? 'পাসওয়ার্ড' : 'Password'} <span className="text-rose-500">*</span>
                  </label>
                  <div className="relative">
                    <Lock className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                    <input
                      type={showPassword ? 'text' : 'password'}
                      required
                      minLength={6}
                      placeholder="••••••••"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      className="w-full pl-10 pr-9 py-2.5 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 cursor-pointer"
                    >
                      {showPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {isBn ? 'কনফার্ম পাসওয়ার্ড' : 'Confirm Password'} <span className="text-rose-500">*</span>
                  </label>
                  <div className="relative">
                    <Lock className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                    <input
                      type={showConfirmPassword ? 'text' : 'password'}
                      required
                      minLength={6}
                      placeholder="••••••••"
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                      className="w-full pl-10 pr-9 py-2.5 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
                    />
                    <button
                      type="button"
                      onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                      className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 cursor-pointer"
                    >
                      {showConfirmPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </div>
              </div>

              {/* 5. Role: Member by Default (Rule 2: Role Security) */}
              <div className="bg-slate-50 p-3.5 rounded-2xl border border-slate-200 space-y-1.5">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-bold text-slate-800">
                    {isBn ? 'অ্যাকাউন্ট রোল (Role Security)' : 'Assigned Role'}
                  </label>
                  <span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-slate-200 text-slate-800 border border-slate-300">
                    {isBn ? 'সদস্য (Member) - ডিফল্ট' : 'Member (Default)'}
                  </span>
                </div>
                <p className="text-[11px] text-slate-600 leading-relaxed">
                  {isBn 
                    ? 'নিরাপত্তার স্বার্থে নতুন সকল অ্যাকাউন্ট সর্বদা "Member" রোলে তৈরি হয়। সাধারণ অ্যাকাউন্ট তৈরির সময় Admin নির্বাচন অনুমোদিত নয়। শুধুমাত্র বিদ্যমান অনুমোদিত এডমিন পরবর্তীতে যেকোনো অ্যাকাউন্টকে এডমিনে উন্নীত করতে পারবেন।' 
                    : 'New accounts are ALWAYS created with Role: Member. Only an authorized Admin can promote an account to Admin later.'}
                </p>
              </div>

              {/* Submit Buttons */}
              <div className="pt-3 border-t border-slate-200 flex items-center justify-end gap-3">
                <button
                  type="button"
                  onClick={() => {
                    setShowAddModal(false);
                    resetAddForm();
                  }}
                  className="px-4 py-2.5 bg-slate-100 text-slate-700 hover:bg-slate-200 rounded-xl text-xs font-bold transition-colors cursor-pointer"
                >
                  {isBn ? 'বাতিল' : 'Cancel'}
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting || !!existingAccountForSelectedMember || !name.trim() || !email.trim() || !password}
                  className="px-5 py-2.5 bg-indigo-700 hover:bg-indigo-800 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-xl text-xs font-bold shadow-sm hover:shadow-md transition-all flex items-center gap-1.5 cursor-pointer"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  <span>{isSubmitting ? (isBn ? 'তৈরি হচ্ছে...' : 'Creating...') : (isBn ? 'অ্যাকাউন্ট তৈরি নিশ্চিত করুন' : 'Confirm & Create Account')}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* Edit Role & Information Modal */}
      {/* ========================================================================= */}
      {editingUser && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
          <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 w-full max-w-lg overflow-hidden my-6">
            <div className="bg-indigo-900 text-white px-6 py-4 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <Edit3 className="w-5 h-5 text-indigo-200" />
                <div>
                  <h3 className="text-base font-bold">
                    {isBn ? 'অ্যাকাউন্ট ও পদবী তথ্য সম্পাদনা' : 'Edit Account Information'}
                  </h3>
                  <p className="text-xs text-indigo-200">
                    UID: {editingUser.userUid || editingUser.id} • {editingUser.name}
                  </p>
                </div>
              </div>
              <button 
                onClick={() => setEditingUser(null)} 
                className="text-indigo-200 hover:text-white p-1 rounded-lg hover:bg-indigo-800 transition-colors cursor-pointer"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleEditUser} className="p-6 space-y-4 max-h-[75vh] overflow-y-auto">
              {editError && (
                <div className="p-3 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-700 flex items-start gap-2">
                  <AlertTriangle className="w-4 h-4 text-rose-500 shrink-0 mt-0.5" />
                  <div>{editError}</div>
                </div>
              )}

              {/* User UID - Read-only */}
              <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 flex items-center justify-between">
                <div>
                  <span className="text-[11px] font-bold text-slate-500 uppercase">{isBn ? 'ইউজার ইউআইডি (UID)' : 'User UID'}</span>
                  <div className="font-mono font-bold text-indigo-700 text-sm mt-0.5">
                    {editingUser.userUid || editingUser.id}
                  </div>
                </div>
                <span className="text-[10px] text-slate-400">{isBn ? 'পরিবর্তনযোগ্য নয়' : 'Immutable'}</span>
              </div>

              {/* Linked Member badge if any */}
              {editingUser.memberNo && (
                <div className="bg-emerald-50 p-3 rounded-xl border border-emerald-200 flex items-center gap-2 text-xs text-emerald-800">
                  <LinkIcon className="w-4 h-4 text-emerald-600 shrink-0" />
                  <span>
                    {isBn 
                      ? `সমিতি সদস্য #${toBengaliNumber(editingUser.memberNo)} হিসেবে সংযুক্ত রয়েছে।`
                      : `Linked with Somiti Member #${editingUser.memberNo}.`}
                  </span>
                </div>
              )}

              {/* Role Selection with Security Constraint */}
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  {isBn ? 'অ্যাকাউন্ট রোল (Role)' : 'Account Role'} <span className="text-rose-500">*</span>
                </label>
                <select
                  value={editRole}
                  disabled={editingUser.id === currentUser?.id && editingUser.role === 'member'} // Members cannot change their own role
                  onChange={(e) => {
                    const r = e.target.value as UserRole;
                    setEditRole(r);
                    setEditRoleTitle(getDefaultRoleTitle(r));
                  }}
                  className="w-full px-3.5 py-2.5 border border-slate-300 rounded-xl text-xs bg-white focus:ring-2 focus:ring-indigo-500 focus:outline-hidden font-medium"
                >
                  <option value="member">{isBn ? 'সদস্য (Member)' : 'Member'}</option>
                  <option value="admin" disabled={activeAdminCount >= MAX_ACTIVE_ADMINS && editingUser.role !== 'admin'}>
                    {isBn ? `প্রধান প্রশাসক (Admin) ${activeAdminCount >= MAX_ACTIVE_ADMINS && editingUser.role !== 'admin' ? '- কোটা পূর্ণ' : ''}` : 'Admin'}
                  </option>
                  <option value="president">{isBn ? 'সভাপতি (President)' : 'President'}</option>
                  <option value="secretary">{isBn ? 'সাধারণ সম্পাদক (General Secretary)' : 'General Secretary'}</option>
                  <option value="cashier">{isBn ? 'ক্যাশিয়ার (Cashier)' : 'Cashier'}</option>
                  <option value="manager">{isBn ? 'ম্যানেজার (Branch Manager)' : 'Manager'}</option>
                  <option value="field_officer">{isBn ? 'মাঠকর্মী / কালেক্টর' : 'Field Officer'}</option>
                </select>
                {activeAdminCount >= MAX_ACTIVE_ADMINS && editingUser.role !== 'admin' && (
                  <p className="text-[10px] text-amber-700 mt-1">
                    {isBn ? '* বর্তমানে ২টি সক্রিয় এডমিন অ্যাকাউন্ট রয়েছে। নতুন এডমিন করতে হলে আগে অন্য এডমিন ডিমোট করুন।' : '* 2 active admin accounts already exist.'}
                  </p>
                )}
              </div>

              {/* Email Address - Rule 4 Sync */}
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  {isBn ? 'ইমেইল এড্রেস' : 'Email Address'} <span className="text-rose-500">*</span>
                </label>
                <input
                  type="email"
                  required
                  value={editEmail}
                  onChange={(e) => setEditEmail(e.target.value)}
                  className="w-full px-3.5 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-indigo-500 focus:outline-hidden font-mono"
                />
                <p className="text-[10px] text-slate-400 mt-1">
                  {isBn ? 'ইমেইল পরিবর্তন করলে সংযুক্ত সদস্য প্রোফাইলেও স্বয়ংক্রিয়ভাবে আপডেট হবে।' : 'Updating email will automatically update the linked member profile.'}
                </p>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {isBn ? 'নাম' : 'Name'}
                  </label>
                  <input
                    type="text"
                    required
                    value={editName}
                    onChange={(e) => setEditName(e.target.value)}
                    className="w-full px-3.5 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
                  />
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {isBn ? 'মোবাইল নম্বর' : 'Phone'}
                  </label>
                  <input
                    type="tel"
                    value={editPhone}
                    onChange={(e) => setEditPhone(e.target.value)}
                    className="w-full px-3.5 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
                  />
                </div>
              </div>

              {/* Status toggle */}
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  {isBn ? 'অ্যাকাউন্ট স্ট্যাটাস' : 'Account Status'}
                </label>
                <div className="flex items-center gap-4 pt-1">
                  <label className="flex items-center gap-2 text-xs font-semibold text-slate-700 cursor-pointer">
                    <input
                      type="radio"
                      name="editStatus"
                      value="active"
                      checked={editStatus === 'active'}
                      onChange={() => setEditStatus('active')}
                      className="text-emerald-600"
                    />
                    <span className="text-emerald-700">{isBn ? 'সক্রিয় (Active)' : 'Active'}</span>
                  </label>

                  <label className="flex items-center gap-2 text-xs font-semibold text-slate-700 cursor-pointer">
                    <input
                      type="radio"
                      name="editStatus"
                      value="inactive"
                      checked={editStatus === 'inactive'}
                      onChange={() => setEditStatus('inactive')}
                      className="text-rose-600"
                    />
                    <span className="text-rose-700">{isBn ? 'স্থগিত (Suspended)' : 'Suspended'}</span>
                  </label>
                </div>
              </div>

              <div className="pt-4 border-t border-slate-200 flex items-center justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setEditingUser(null)}
                  className="px-4 py-2 bg-slate-100 text-slate-700 rounded-xl text-xs font-bold cursor-pointer"
                >
                  {isBn ? 'বাতিল' : 'Cancel'}
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-indigo-700 hover:bg-indigo-800 text-white rounded-xl text-xs font-bold shadow-sm cursor-pointer"
                >
                  {isBn ? 'সংরক্ষণ করুন' : 'Save Changes'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {userToDelete && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 w-full max-w-sm overflow-hidden p-6 text-center space-y-4">
            <div className="w-12 h-12 rounded-full bg-rose-100 text-rose-600 mx-auto flex items-center justify-center ring-4 ring-rose-50">
              <Trash2 className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                {isBn ? 'অ্যাকাউন্ট মুছে ফেলতে চান?' : 'Delete this account?'}
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                {isBn 
                  ? 'এই ব্যবহারকারী অ্যাকাউন্ট মুছে ফেললে তিনি আর সফটওয়্যারে লগইন করতে পারবেন না।'
                  : 'Deleting this account will permanently revoke their software access.'}
              </p>
            </div>
            <div className="flex items-center justify-center gap-3 pt-2">
              <button
                onClick={() => setUserToDelete(null)}
                className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-bold transition-colors cursor-pointer"
              >
                {isBn ? 'বাতিল' : 'Cancel'}
              </button>
              <button
                onClick={() => confirmDelete(userToDelete)}
                className="px-4 py-2 bg-rose-600 hover:bg-rose-700 text-white rounded-xl text-xs font-bold shadow-sm transition-colors cursor-pointer"
              >
                {isBn ? 'হ্যাঁ, মুছুন' : 'Yes, Delete'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
